// Auto-generated by eval/difffdn/export_cpp_header.py
// Do not edit by hand.
#ifndef TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
#define TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP

#include <cstddef>
#include <cmath>

namespace DISTRHO {

struct DiffPreset {
    const char* configId;
    int sr;
    const char* delaySetName;
    int delaySetId;
    float rt60;
    int delay_samples[4];
    float gains[4];
    float u_unit[4];
    float b[4];
    float cL[4];
    float cR[4];
};

constexpr std::size_t kDiffPresetCount = 3u;
constexpr DiffPreset kDiffPresets[kDiffPresetCount] = {
    {
        "householder_prime_sr44100",
        44100,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.919562276f, 0.875487112f, 0.835298293f, 0.780890057f },
        { -0.337588661f, 0.0889583091f, -0.926579173f, 0.139897649f },
        { 0.25f, 0.25f, 0.25f, 0.25f },
        { 0.5f, -0.5f, 0.5f, -0.5f },
        { 0.5f, 0.5f, -0.5f, -0.5f },
    },
    {
        "householder_prime_rt60_2p8_ad005",
        48000,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.925849036f, 0.884997338f, 0.847601983f, 0.796740629f },
        { -0.341253631f, 0.0876904242f, -0.9259671f, 0.135798667f },
        { 0.25f, 0.25f, 0.25f, 0.25f },
        { 0.5f, -0.5f, 0.5f, -0.5f },
        { 0.5f, 0.5f, -0.5f, -0.5f },
    },
    {
        "householder_spread_rt60_2p8_ad005",
        48000,
        "Spread",
        1,
        2.8f,
        { 1200, 1800, 2400, 3000 },
        { 0.940187095f, 0.91163592f, 0.883951773f, 0.857108327f },
        { -0.313519943f, 0.109637571f, -0.927129485f, 0.173538947f },
        { 0.25f, 0.25f, 0.25f, 0.25f },
        { 0.5f, -0.5f, 0.5f, -0.5f },
        { 0.5f, 0.5f, -0.5f, -0.5f },
    },
};

inline const DiffPreset* findDiffPreset(int sr, int delaySetId, float rt60Approx) noexcept
{
    const DiffPreset* best = nullptr;
    float bestDist = 0.0f;

    for (std::size_t i = 0; i < kDiffPresetCount; ++i) {
        const DiffPreset& p = kDiffPresets[i];
        if (p.sr != sr)
            continue;
        if (delaySetId >= 0 && p.delaySetId != delaySetId)
            continue;

        const float dist = std::fabs(p.rt60 - rt60Approx);
        if (best == nullptr || dist < bestDist) {
            best = &p;
            bestDist = dist;
        }
    }

    return best;
}

} // namespace DISTRHO

#endif // TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
