// Auto-generated by eval/difffdn/export_cpp_header.py
// Do not edit by hand.
#ifndef TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
#define TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP

#include <cstddef>
#include <cmath>

namespace DISTRHO {

struct DiffPreset {
    const char* configId;
    int sr;
    const char* delaySetName;
    int delaySetId;
    float rt60;
    int delay_samples[4];
    float gains[4];
    float u_unit[4];
    float b[4];
    float cL[4];
    float cR[4];
};

constexpr std::size_t kDiffPresetCount = 3u;
constexpr DiffPreset kDiffPresets[kDiffPresetCount] = {
    {
        "householder_prime_sr44100",
        44100,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.919562276f, 0.875487112f, 0.835298293f, 0.780890057f },
        { 0.262667224f, 0.060124821f, -0.831174541f, 0.486353593f },
        { 0.108545957f, 0.231033593f, 0.958319366f, 0.128316981f },
        { 0.128188561f, -0.685836118f, 0.129073459f, -0.704653499f },
        { 0.5581882f, 0.716242793f, -0.395469854f, -0.137934002f },
    },
    {
        "householder_prime_rt60_2p8_ad005",
        48000,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.925849036f, 0.884997338f, 0.847601983f, 0.796740629f },
        { 0.272775853f, 0.0530866863f, -0.82469942f, 0.492591113f },
        { 0.104534858f, 0.21970601f, 0.960968579f, 0.131685694f },
        { 0.130763323f, -0.712003031f, 0.127410961f, -0.678025873f },
        { 0.53593613f, 0.736427661f, -0.390543641f, -0.133874674f },
    },
    {
        "householder_spread_rt60_2p8_ad005",
        48000,
        "Spread",
        1,
        2.8f,
        { 1200, 1800, 2400, 3000 },
        { 0.940187095f, 0.91163592f, 0.883951773f, 0.857108327f },
        { 0.359576749f, 0.483160021f, -0.551915914f, 0.576757991f },
        { 0.0218171817f, 0.0442183438f, 0.961907775f, -0.268890647f },
        { 0.335438654f, 0.369082107f, 0.0561616805f, -0.864930733f },
        { 0.332737742f, 0.367833925f, 0.0575359792f, -0.86641411f },
    },
};

inline const DiffPreset* findDiffPreset(int sr, int delaySetId, float rt60Approx) noexcept
{
    const DiffPreset* best = nullptr;
    float bestDist = 0.0f;

    for (std::size_t i = 0; i < kDiffPresetCount; ++i) {
        const DiffPreset& p = kDiffPresets[i];
        if (p.sr != sr)
            continue;
        if (delaySetId >= 0 && p.delaySetId != delaySetId)
            continue;

        const float dist = std::fabs(p.rt60 - rt60Approx);
        if (best == nullptr || dist < bestDist) {
            best = &p;
            bestDist = dist;
        }
    }

    return best;
}

} // namespace DISTRHO

#endif // TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
