// Auto-generated by eval/difffdn/export_cpp_header.py
// Do not edit by hand.
#ifndef TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
#define TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP

#include <cstddef>
#include <cmath>

namespace DISTRHO {

struct DiffPreset {
    const char* configId;
    int sr;
    const char* delaySetName;
    int delaySetId;
    float rt60;
    int delay_samples[4];
    float gains[4];
    float u_unit[4];
    float b[4];
    float cL[4];
    float cR[4];
};

constexpr std::size_t kDiffPresetCount = 3u;
constexpr DiffPreset kDiffPresets[kDiffPresetCount] = {
    {
        "householder_prime_sr44100_bank_seed0_r2_full",
        44100,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.919562276f, 0.875487112f, 0.835298293f, 0.780890057f },
        { 0.333572459f, -0.395397874f, -0.463094689f, -0.719675792f },
        { 0.202245221f, 0.0725561412f, -0.169450644f, 0.961831044f },
        { 0.269495872f, 0.0847342882f, -0.111478771f, -0.952766791f },
        { 0.242084732f, 0.189726278f, -0.12196867f, -0.943675032f },
    },
    {
        "householder_prime_rt60_2p8_paper_seed2_u_only",
        48000,
        "Prime",
        0,
        2.8f,
        { 1499, 2377, 3217, 4421 },
        { 0.925849036f, 0.884997338f, 0.847601983f, 0.796740629f },
        { 0.330228639f, -0.146919874f, -0.240511594f, -0.900842811f },
        { 0.25f, 0.25f, 0.25f, 0.25f },
        { 0.5f, -0.5f, 0.5f, -0.5f },
        { 0.5f, 0.5f, -0.5f, -0.5f },
    },
    {
        "householder_spread_rt60_2p8_bank_seed2_r2_full",
        48000,
        "Spread",
        1,
        2.8f,
        { 1200, 1800, 2400, 3000 },
        { 0.940187095f, 0.91163592f, 0.883951773f, 0.857108327f },
        { -0.778021342f, 0.398096678f, 0.363794111f, -0.322266461f },
        { 0.663273652f, 0.110869334f, 0.203550561f, 0.711577981f },
        { 0.446384813f, -0.634883848f, 0.165597058f, -0.608474086f },
        { 0.949621201f, 0.148175432f, 0.00888849147f, -0.276015599f },
    },
};

inline const DiffPreset* findDiffPreset(int sr, int delaySetId, float rt60Approx) noexcept
{
    const DiffPreset* best = nullptr;
    float bestDist = 0.0f;

    for (std::size_t i = 0; i < kDiffPresetCount; ++i) {
        const DiffPreset& p = kDiffPresets[i];
        if (p.sr != sr)
            continue;
        if (delaySetId >= 0 && p.delaySetId != delaySetId)
            continue;

        const float dist = std::fabs(p.rt60 - rt60Approx);
        if (best == nullptr || dist < bestDist) {
            best = &p;
            bestDist = dist;
        }
    }

    return best;
}

} // namespace DISTRHO

#endif // TINY_FDN_REVERB_DIFF_FDN_PRESETS_HPP
